server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mariadb://192.168.45.202:13306/gamja
    username: phobikim
    password: phobikim8038!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true